### ISSUE TITLE
i made the thumbnail in left side of the image like amazon but its throwing error in js 

### ISSUE THREAD

**Issue by naseerkhan** [payalord/xZoom#74]
please check the code :

````
<div class="xzoom-container d-flex">
   <ul class="xzoom-thumbs">
      <li><a href="../img\Images\new\14072020051921_3.jpg"><img class="xzoom-gallery5 img-fluid" width="80" height="80" src="../img\Images\new\14072020051921_3.jpg" xpreview="../img\Images\new\14072020051921_3.jpg"></a></li>
      <li><a href="../img\Images\new\productImages\13072020041403_2.jpg"><img class="xzoom-gallery5 img-fluid" width="80" height="80" src="../img\Images\new\productImages\13072020041403_2.jpg" xpreview="../img\Images\new\productImages\13072020041403_2.jpg"></a></li>
      <li><a href="../img\Images\new\productImages\14072020052045_1.jpg"><img class="xzoom-gallery5 img-fluid" width="80" height="80" src="../img\Images\new\productImages\14072020052045_1.jpg" xpreview="../img\Images\new\productImages\14072020052045_1.jpg"></a></li>
      <li><a href="../img\Images\new\productImages\14072020052100_2.jpg"><img class="xzoom-gallery5 img-fluid" width="80" height="80" src="../img\Images\new\productImages\14072020052100_2.jpg" xpreview="../img\Images\new\productImages\14072020052100_2.jpg"></a></li>
   </ul>
   <img class="xzoom5 img-fluid" width="450" id="xzoom-magnific" src="../img\Images\new\14072020051921_3.jpg" xoriginal="../img\Images\new\14072020051921_3.jpg">
</div>
````

error  : 
   

xzoom.min.js:658 Uncaught TypeError: Cannot read properties of undefined (reading 'x')
    at HTMLImageElement.<anonymous> (xzoom.min.js:658:42)
    at Function.each (jquery.min.js:2:2861)
    at n.fn.init.each (jquery.min.js:2:845)
    at n.fn.init.Ao.fn.xzoom (xzoom.min.js:644:26)
    at drawimageslider (productdetail.aspx?Id=34:4607:53)
    at Object.success (productdetail.aspx?Id=34:4542:21)
    at i (jquery.min.js:2:27151)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:27914)
    at z (jquery.min.js:4:12059)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4:15619)

**Comment by payalord** [comment]
What version of jQuery you are using? Also please make sure all your images is available by their urls. And you can also check sandbox to compare your case with working examples here:
* https://github.com/payalord/xzoom-sandbox/tree/master/ThumbsFirst
* https://github.com/payalord/xzoom-sandbox/tree/master/ThumbsFirstHammerMagnific

Their corresponding test urls are:
* https://payalord.github.io/xzoom-sandbox/ThumbsFirst/
* https://payalord.github.io/xzoom-sandbox/ThumbsFirstHammerMagnific/

**Comment by payalord** [comment]
Closing due to no activity.
